/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryForm: typeof import('./components/CategoryForm.vue')['default']
    Entity: typeof import('./components/Entity.vue')['default']
    'Entity.': typeof import('./components/Entity.vue')['default']
    'Entity.js': typeof import('./components/Entity.js.vue')['default']
    EntityTable: typeof import('./components/EntityTable.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/Main.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    ProductForm: typeof import('./components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
  }
}
